sudo: false
language: rust

matrix:
  allow_failures:
    - rust: nightly
  include:
    - rust: nightly
      env: FEATURES=nightly
    - rust: nightly
      env: FEATURES=''
    - rust: beta
      env: FEATURES=''
    - rust: stable
      env: FEATURES=''
script:
  - cargo test --features "$FEATURES"
